feature: Implement EF entities and configure the DbContext
the-17th-fox/Car-Auction-ASP.NETCore pull request #2
Opened 2022-04-19 18:38 UTC by the-17th-fox

### What & How

Implement entities according to the db schema. Users and DbContext should support the Identity.
After all configure the main class.

### How

Every entity is derived from BasicEntity (consists of an Id field only), as exception User derives also the IdentityUser class.
In the context were added shadows properties for Users and Cars tables: updatedAt, createdAt.
Lots and auctions use enums with status codes.
In the main class the DbContext and Identity config were added to the builder.

### Affected Area

CA.WebAPI
Core/CA.Domain.Entities
Core/CA.Domain.Enums
Infrastructure/CA.Persistence.Context

### PR Checklist

*Build*

 - [x] Build Succeeded

2022-04-20 16:39 UTC, TsvirkoNikita commented
After you will be done with the requested changes, add a migration

2022-04-20 16:40 UTC, TsvirkoNikita requested changes

2022-04-20 16:40 UTC, TsvirkoNikita commented on Core/CA.Domain/Entities/User.cs
> +        public List<LotBid> Bids { get; set; } = new();
What is the LotBid? Looks like a typo

2022-04-20 16:40 UTC, TsvirkoNikita commented on Core/CA.Domain/Entities/Lot.cs
> +        public LotBid? LastBid { get; set; }
The same

2022-04-20 16:54 UTC, the-17th-fox commented on Core/CA.Domain/Entities/Lot.cs
> +        public LotBid? LastBid { get; set; }
Thanks, got it

2022-04-21 16:45 UTC, the-17th-fox commented
Fixed all bugs (with relationships and small typos)
Added non-nullable properties (as well updated DbSets in the context)
Implemented overrided method for SaveChangesAsync
Configured the DeleteBehavior for some tables
And added new initial migration

2022-04-22 13:01 UTC, TsvirkoNikita commented
Please, think about reworking the relationship between the Car and Lot entities to one-to-many. A lot can be canceled and unclaimed, so, cars could have related to multiple lot entities.

2022-04-24 07:48 UTC, TsvirkoNikita approved these changes

2022-04-25 08:44 UTC, merged